services:
  frontend:
    container_name: tour-graph
    image: ghcr.io/benja971/tour-graph:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:3010:3000'
    networks:
      - infra-net

networks:
  infra-net:
    external: true
